import 'package:flutter/material.dart';

List<IconData> iconListForCategories = [
  Icons.child_care_rounded,
  Icons.phone_android_rounded,
  Icons.king_bed_outlined,
  Icons.book,
  Icons.watch,
  Icons.music_note,
  Icons.sports,
  Icons.add_to_photos,
];

String locationIconForFee =
    "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAACRXAAAkVwEKohbLAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAACoxJREFUeF7tnX+MVFcVx++5s7PSXWB2CUqRysxQfrSW+Cs1mkatJq3aVP/RaJpQsQGU0mAaI7RUYaePH2Ji/ItSNcYYjQYLttZQo438Y+vPaonWqlv5sbtUwAK7O7MsuLAz93ju7LGisPJg733v3jf3k5B3z9kNM3vv95173/u+HyCyym7MdfX2LVUit0QqtQgBFgnEhULALPppBwicSe3pE7+MoyhghBpnqT0EAg7Q9qCS8oAUjZeqN5RfFB+HxsTvZovsCKCCslv2v4NatyoB76btu+iPo0GeOijECInnWRLJs22IPx8SpedEBIp/7DXeC6B788BNCtXHAMVyAVDmtFUQ8ShtHpco9wxHxV9MZP3ESwHMrRzt+KccX0G75lr6C5ZwOhWoOvSS+B65BvPfOh7NoynEL7wSwPTK0dkSxlfS/H0/AMzltCPgKRLDTpXP7zj9+esGOek8fgig0jetS8I6Kr0baOA7OeskSAtK6tTt1a7xr4j7F5/jtLM4L4BCZeA2IXEHfdEbOOUHiIcQ5EO1SnEPZ5zEWQF0Vg6+rk3mvkmHZB/ilJdQ1dpbx8aqM9HCE5xyCicFUIj63keb79Lgv34i4z0nlFDLRyoLnubYGdwSQAXbCrJ/I62qN9IhXY6z2YBKAS0Sd9TmDq4Tq28e52zqOCOAOV8+3jl25tweAHEHpzIK7stNG/vI4IM3nuZEqjghgJmVI7NANvZSyb+FU9kG8Xf1/Pido19YfJIzqZG6ALq2HC6ikj+lL+LXKn+q0FGCyskPjGwqHuJMKqQqgFmVl69ryMYv6UvM51RLQWuCI7mcvGVo43x9ajkVJG8Tp/tLhwoNaDzVqoOv0X97o954urB9oJtTiZOOACp909SY3EsLvjdzpmUBgJvEeXxS9wmnEiUVARRAfIP+cG3ZBgiqBO8pSPgah4mS+Bqga/PAcloAfZvDwIWguLv6cOl7HCVCogKYuWXgelC4nz7UyIUaWUMbSQoabzvds/AAp6yT3BSwG3OyoXaFwZ8cEDBdYtt3dF9xyjqJCaDrLwP30orn7RwGJoF2kHcWeo+s5NA6iUwB+jAHzqu/0cfN5lTg/4JDjXx+cRIXliRTAc7h1jD4VwLMkuPjmziwivUKMGPzwUU5lftr5tw962AdlVxSi4qHOWEF6xUgh7n1YfCvBmgTgJ/jwBpWK0DntkNz2uq5fvqQVM5y+Q4KMdausHwyKv+DU8axWgHydfnZMPhXj+678xLWcmgFexWg8mJ7l+w8Th+hb8UKXDV4qqrOzBPR0vOcMIq1ClCQnXeGwTcBzO4SMz7IgXGsCQAQPsHNwFSR6m5uGcfKFKAv8ZKgjtH//hpOBaaAXgwKhXNrUbnKKWNYqQAS6h8Og28OvRgEAJpSzWNFAAhwOzcDhkAQVvrUvACQhh/hNo4CxsDbdd9yYAzjAuja0vcmqllzOAwYQt8l1b3lyBs5NIaFCiBv5VbAMKjwvdw0ho01wFt4GzAOGu9bGwJ4K28D5jF+FbVZAXz993k6aL2Ro4BhUIilpi8XMyqA7ldeuzgc/9sDAK6Z0du3kEMjmK0ADVXkVsASgDmjd1IZFYDKiWu5GbAEgJrHTSMYFQBgZp7o4SyAwmgfGxUALVKCACyDCO5WAFJAgVsBWwAa7WOzU4DAcARgGRCinZtGMDsFhEPABIA8N4xguAKAUXXGBoUzT92yDaLZnczwGsC8XRkLEEb3ilbCrAAAnHj0WZahdZbRPjZcAYR+60bAJiDcFQAKDAKwDUKNW0YwPAUIo18ucEmM7mSm1wBHuBWwBEoc4KYRDK8BMNWnXrYC0ECjt4sbFQBIs18ucDEy32Z0JzMqgOqS8t9pY+UmxoBeZIuxofE3HOfQCGanAP1yRcQ/cRQwDAjxgun3FZoVAIEgfsPNgGEQ0XjfGhcAAPgjABTnqFeHqVHnjNPQYLkvAAXwa266j3YvAbqp0cYZp1EojPetcQHoFyDQYiWcDzBPfy0q93PbGMYF0ATxSW4FzPFD3hrFkgDgR9wKmEIpKzuVFQHURPEZqgLevD/Xeagvq6L8K46MYqcCRFCnBdYTHAWmCALsbvapBewIQAO4k1uBKQIgv8pN41gTQLVnwR9RoJWy1UrQEdUz1Z751s6u2qsABCA8ys3AVSIBre39GqsCqOKofnW68WPX1gEPDzfOWF1LWRVA8/GmKHo4ClwpIDbZekTsv7ErAKKKRf0WrD9MRIG40Nz/QrVR+j6H1rAugKZ9qUjJgStCCtxg2vq9FPYFQFSj0lOk6R9wGLgciLuHK+WfcGSVRASgqav2NVTXXuEwMCl4ahwbn+HAOokJYDSad0qAWs1hYBJQwZoz0cITHFonMQFoqpUF2iR6bCIKXILHalEp0akyUQFoUOG9iOJlDgMMCjymlLyPw8RIXAD6mfcIsJIWOnSkE2hCfUEDsWokmj/EmcRIXACakUrxZyjA6ilOn0AQjya16v9fUhGApgPz66nuvcRh64J4qF11bOAocVITwPFo3lmUsIxE0DJP97gYrDcAl52M5oxyInFSE4Cm1lN8nhY/2zlsOWgRtO10ZcFvOUyFVAWgqWFpC22em4haCdxfu3ZwGwepkboA9KVOOYWfpEpwljOZh/b8MQC5XKy+OfXpL30BEINRuRcQUlsIJQ0IsX64p/hnDlMlnad6XQpEKEQDPwYQd3Amo+C+ak/p/QLAifMgTlSAJtQhuTb5KeqgxE+GJEgVlFrpyuBr3BEAMbRx/lGqSYk5YUkDiPcNR9c7dducO1PABRQe7t9FU8FdHGaFJ6qV0ke57QxOVYBXQVyTJcOIjR6a3tzDSQFkyjBK0eiJg5sVgGgaRiC8v6+AFLwzLaMnDs4KQNOh2h+gHvTXMNJGD3Y8xJGTOC0Avw2j9I2eODgtAE3TMAL8IofeQKU/daMnDs4LQFNTpa3Uo8535n9ww+iJgxcCaBpGiPf4YBjRnu+M0RMHPwRA+GIYuWT0xMHJM4GT4rxh5JbREwdvKkAT6tg2hFXU0S6eVKmCrK/wafA1fgmAGIyKx6iL13LoDDTua4Y3LfLu9LVfU8AFOGYYOWn0xMG7CvAqjhhGLhs9cfBWANowEggrUjWMHDd64uBvBSBqUXFfmoYRKc9poycOXgtAk5ph5IHREwfvBZCOYeSH0RMH7wWgSdwwQtjqg9ETh0wIQJOcYYT7q3NPeedOTkZmBJCEYeSb0ROH7AiAaBpGAh7k0DiAYp1PRk8cvD0TOCnWDCP/jJ44ZKoCNLFjGHlp9MQhewIgtGGEAj7N4ZTx1eiJQyYFoKlVSo8jiik/a5d2+V3DPWXrz+xNi8wKoMkUDSNt9KCSzlnPJsm0AKZkGGXA6IlDtisA0TSMhLji9xchiEd8N3rikHkBaGoo1tMOHfv4nQTT26HaW+KJJS0hABGVx2iXXk4jG+MMHtaVUPdok4kTmaY1BEDUotL+WIZRhoyeOLSMADSXNYwQn8+S0ROHlhKANoxUDpbR4d1FPr42kRoSl2XJ6IlDawmA0K+3BwEXXckDCA+c7lnQcs8uzp4ZFIeLDKNsGj1xaLkK0OS/DaPMGj2By9C9ue8u/Y/DFkSIfwEUONCtg4gSFgAAAABJRU5ErkJggg==";

String locationIconForFree =
    "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAFzUkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAACpZJREFUeF7tnX+MVFcVx895s7ulu8DsklpEKrNL+SFC/JUaTaOiSf3RUP8osIiC0ADW0mCMESpNWo2R2r/8i1JNjTE1NpSdWX4IxjbyT1t/Vku0tpHKj92lAhbY3ZmFhYWZecdzd46kLV15sPe+d++b+0ng3XN2CfPu/b5z733fmTcIaYU6M609uCDM0NwgpNmEMBsIZgHCFABsRqLJ3J5Y+104R4hD3DjP7QFEOMTHw2GAh4IqvlbsoFcA89XR300Z6REAfS9o6331Y3xKC0OkT3LmEwg4ufbD8UFAQ/zXCyySFxoInxton/ci4PdD+bHTOC+Atr4l88Mw6ESgVYDYIWmjENFxPnQHAeYHc/nf1bJu4qQAph2/q/lCecIabm7gU5hbyyYDARzkTnzsxsYLPz85fd95STuDUwKYePzLNwXlylok+CbP09MkbQdEZwhwW9hY3nr2lt39krUeNwTQs3pCKw5vJILNiNgiWSvh6eEcrz0eLZbP/gjmPHNR0tZivQCyfcvu4F7dyi/0fZJyA6IjFMCDpVwhLxkrsVYALYfvvrkh0/AzLvV3ScpJuCLsrVSr64Zn7TolKauwUgDZnmWfAQh/yeX+PZJynVNhiKuGZnY9K7E12CUAWtiQ7b35Id7SPcRbuoxk0wFxMQDaWuqfshFue6Is2cSxRgBTT65sGbl4Mc8v6E5JpROi/ZmRS4v75/3qbC2RLFYIYPKxpVOwint5vr9dUumG6C+VMiw6N6dwWjKJkbgAWo8uzlGQeYZfiFur/PHCu4QwyHx+KLfjiGQSIVEBTHn97luq1czved88Q1J1Ba8JjmUCuH1gRkHdWk6EQI6x03akM8uDv69eB1+hzr1axWezfV9pk1TsJCOAntUTwgD2cgd8UDJ1C6975gNd2q36RFKxkogAsjD8Uz5xZdl6GL4QPpXF4Z9IGCuxrwFa+5auAsInJfS8BVpZbC88JUEsxCqAyX1fuhWpeoAVr+WNGmlDGUlhNfzI2Vk7D0nKOPFNAdSZCcLqdj/4Y4OIE4OG4BeqryRlnNgE0NoH9/EZflRCzxjwBfLx7DFYK6FxYpkC1DYHw0v/YgHcJCnP/4NooNpYmRPHG0viqQBU3uIH/xpAnBKUGx6WyCjGK8Ckw4tnZzLBP/mk0uXumYagQkF1bim386hkjGC8AvDgb/KDfx0gNABlvi2RMYxWgJYjy6c2ZCq9vLBJ5C6X6xDQSBNhx+mO/H8kpR2jFaAxqHzLD/71o/ruEtIGCY1grgK80tnU2kIn1YJGMp7rgehMcRinw4L8JcloxVgFyLbQIj/4GuDdU+sk+oJE2jEmAET4qjQ94yXEldLSjpEpQL3FKwjxBDdvqGU840EtBoHK00ode4qS0oaRChBU8It88IOvCbUYRGxcJKFWjAiAED4rTY8mCMz0qX4BEE//SHdI5NEFsQC4byXShnYBtPYs+wAXrakSejShPiXVdmzJ+yXUhv4KENBCaXk0QxR8WpraMLEG+JAcPboh/X1rQAD0YWl4tEPa30WtVwB/vbeRZ6t5Enk0wzuBBbrfLqZVAG3v6p/DB7//NwQvBG+c1EOzJNSC3goQZnLS8hgCM6D1k1RaBRACvVuaHkNgiNOlqQWtAkCktDzRw1oQQGsfaxUAL1K8AAxDCPZWACYrR48pSG8f650CyO8ATMNTQJM0taB5CkAvANMgNUpLC5oXgXrV6bkS3ReZ3jUA8RLF4xR6BYBoxaPP0gwSae1jvQJQX6zgMY29AiACLwDTIJSkpQXNFUDvi/O8I1ovMs1rADgmLY8heJ3dJ00t6BUABYk+9bIeQEKtHxfXKgCkitHPsnt4wBpCrReZVgEUOzL/5jJg5EOMHu5ZoJGB984/KaEWNK8B8lUg/IdEHs0gwMu6v69QrwAYVumfpOnRDG+ztfetdgEgoksCuMi9OsiqrUhsNQHo71vtAggx+KM0XeAGVmwb19YGia0mBP19a8S8yfYu7cM6fgy8Gai32F7Q/tW42ivAKAS7peXRxy45asWMABD2SMujizAwclEZEUApd/p5rgLOfH+u9XBfFjve+INEWjFUAZ7jVTXtlMgzTgipq9an+jEjAAUF26TlGScYwI+lqR1jAijO7Po7ERgpW/UEAT1fnFEwdnfVXAVgEOlxaXquk4DMXf0KowIonsM8a7hXQs+1QnB0cBiNrqWMCkAeb/rdWuC5duhhU4+I/R9mBcAUc/Of4hP5m4SeiBDAy8X2+U9LaAzjAqjZl6xkzzURULhZt/X7TpgXAFNs794HRAUJPVeDqGuwo/s3EhklFgEoKk2N6/nM3pDQMxZEZ8rV6jckMk5sAjg3ffsZCOnrEnrGgBDWD8/adUpC48QmAEVxZvcePsUdEnqugHaU2guxTpWxCkBBVL6PgF6X0CMQ0YkwgPsljI3YBaCeec9lbq26xykpD/dFALRuaEZhQDKxEbsAFEO5wm9ZBEZvcboEj//jca36304iAlA0N17YxKf+moT1C9GRpmbcLFHsJCaAk9P3nSfEFdwDZUnVHwSVKtGK01Pz5yQTO4kJQFHK5V8igkclrDt4EfTI2Zndf5YwERIVgKLUfvoH3BUvSlg/EB0o9bc9IlFiJC4A9VanDIWruRKcl0zq4UXfCAa0Cm57IvHpL3kBMP0dOw8iUmILobhBgE2Due5XJUwUe57qRYDZvs5f8wu6UzLphGh/sb3wOe55K+6DWFEBRuEOyQT0Ne6g2G+GxEgRQ1xry+Ar7BEAMzCjcJwPsTlhcYME9w/emrfqMTr2TAFvItvbuZ1f2HIJ08LOYnt+ibStwaoKcBm6tD5NhlHN6OHpzUKsFECqDKMEjZ4o2FkBmFHDCNz/XAGfw7akjJ4oWCsARXPTyAPche4aRjWj50GJrMRqAThtGFlg9ETBagEoaoYR/lBCZ7DB6ImC9QJQlNpPbeGD9Z15GUuMnig4IYCaYVS9xwXDiBd91hg9UXBDAIwrhpFNRk8UrLwTOCa2G0aWGT1RcKYCjMId24CZdZYaRkWsZNa4NPgKtwTA9OeePoGAGyS0BiRaPzh7h3O3r92aAt6EZYaRlUZPFJyrAJexxDCy2eiJgrMCUIYRYLBG7bskFT/8f9ts9ETB3QrAlHJd+3kMEjOM+P+22uiJgtMCUCRmGDlg9ETBeQEkYhg5YvREwXkBKGI3jJC2uGD0RCEVAlDEZhgRHSiemeKcOzkWqRFAHIYRL/qcMnqikB4BMGIYfUdC7SDgRpeMnig4eydwTEwZRg4aPVFIVQUYxYxh5KTRE4X0CYBRhhFhcK+E48ZVoycKqRSAotTe1c2X67iftcsLv+2DHQXjz+xNitQKYJRxGkbK6KEArLOedZJqAYzLMOJ/47rRE4V0VwBGDKNr/v4iVsxjrhs9UUi9ABQlaNlEBJH37zz4B5ubLtTFE0vqQgDQ8eQIIK7iob36HTyCShiG9yiTSTKppj4EwPCu4EAkwyhFRk8U6kYAiqsaRgQvpcnoiUJdCUAZRiEGK3h7d4WPr0wk5fGnyeiJQn0JgBnK7TiCCFe8k4dzD5ydWai7ZxenzwyKwtsNo5QaPVGouwowylsNo9QaPZ6r0NazdLn6I2EdAvBfByzidIxLIkoAAAAASUVORK5CYII=";

final data = {
  'Bebek ve Çocuk': {
    'Giyim': ['apron', 'beşik', 'Bebek Önlüğü', 'bonet', 'kızak', 'karyola'],
    'Oyuncak': ['marakas', 'emzik', 'dondurma']
  },
  'Elektronik': {
    'Bilgisayar & Telefon': [
      'cep telefonu',
      'bilgisayar klavyesi',
      'masaüstü bilgisayar',
      'çevirmeli telefon',
      'dijital saat',
      'dijital kol saati',
      'el bilgisayarı',
      'sabit disk',
      'iPod',
      'dizüstü bilgisayar',
      'hoparlör',
      'mikrofon',
      'modem',
      'bilgisayar faresi',
      'notebook',
      'radyo'
    ],
    'Fotoğraf & Kamera': [
      'ateş ekranı',
      'monitör',
      'yazıcı',
      'projeksiyon cihazı',
      'refleks kamera',
      'ekran',
      'televizyon'
    ],
    'Oyun': ['eğlence merkezi', 'uzaktan kumanda'],
    'Pişirme': [
      'kokteyl çalkalayıcı',
      'espresso makinesi',
      'mikrodalga fırın',
      'ekmek kızartma makinesi',
      'el feneri',
      'waffle makinesi'
    ],
    'Temizlik': [
      'bulaşık makinesi',
      'elektrikli fan',
      'saç kurutma makinesi',
      'ütü',
      'çim biçme makinesi',
      'elektrik süpürgesi',
      'çamaşır makinesi'
    ],
    'Diğer': [
      'matkap',
      'terazi',
      'dikiş makinesi',
      'ısıtıcı',
      'spot ışığı',
      'kronometre',
      'elektrik anahtarı',
      'masa lambası',
      'teyp çalar'
    ],
  },
  'Ev Eşyaları': {
    'Bahçe': [
      'varil',
      'el arabası',
      'süpürge',
      'çit',
      'zincirli testere',
      'sandık',
      'paspas',
      'yağmur varili',
      'sallanan sandalye',
      'kürek',
      'pencere teli'
    ],
    'Mobilya': [
      'analog saat',
      'çöp kutusu',
      'banyo havlusu',
      'kitaplık',
      'sandık',
      'komodin',
      'vitrin',
      'çalışma masası',
      'dosya dolabı',
      'katlanır sandalye',
      'dört direkli yatak',
      'kum saati',
      'lamba şapkası',
      'ilaç dolabı',
      'sinek teli',
      'kağıt havlu',
      'yastık',
      'tuvalet pompası',
      'yorgan',
      'duş perdesi',
      'sürgülü kapı',
      'sabunluk',
      'çekyat',
      'paspas',
      'vazo',
      'duvar saati',
      'gardırop',
      'lavabo',
      'stor perde',
      'yün',
      'tuvalet kağıdı'
    ],
    'Mutfak': [
      'kova',
      'kazan',
      'konserve açacağı',
      'satır',
      'kahve kupası',
      'kahve cezvesi',
      'tirbuşon',
      'yavaş pişirici',
      'yemek masası',
      'döküm tencere',
      'kızartma tavası',
      'kepçe',
      'ölçü kabı',
      'süt tenekesi',
      'karıştırma kabı',
      'sürahi',
      'tabak rafı',
      'çevirme makinesi',
      'tuzluk',
      'çorba kasesi',
      'spatula',
      'ocak',
      'süzgeç',
      'çaydanlık',
      'tepsi',
      'wok tava',
      'tahta kaşık',
      'tabak',
      'hotpot',
      'fincan'
    ]
  },
  'Eğitim': {
    'Kırtasiye': [
      'abaküs',
      'sırt çantası',
      'tükenmez kalem',
      'deney kabı',
      'klasör',
      'zarf',
      'dolma kalem',
      'posta çantası',
      'kep',
      'kalem kutusu',
      'kalemtıraş',
      'tüylü kalem',
      'silgi',
      'cetvel',
      'hesap cetveli',
      'stetoskop'
    ]
  },
  'Giyim ve Aksesuar': {
    'Aksesuar': [
      'tokalı kemer',
      'zincir',
      'yüz pudrası',
      'saç tokası',
      'saç spreyi',
      'mendil',
      'ruj',
      'losyon',
      'maske',
      'kolye',
      'parfüm',
      'şapka',
      'güneş kremi',
      'peruk'
    ],
    'Kışlık': [
      'hırka',
      'Noel çorabı',
      'pelerin',
      'tüy boa',
      'kürk ceket',
      'makosen',
      'eldiven',
      'üst etek',
      'çorap',
      'sweatshirt',
      'trençkot'
    ],
    'Resmi': [
      "mezuniyet cübbesi",
      'papyon',
      'gecelik',
      'kimono',
      'laboratuvar önlüğü',
      'çanta',
      'takım elbise',
      'Windsor kravat'
    ],
    'Yazlık': [
      'abaya',
      'sütyen',
      'takunya',
      'kovboy şapkası',
      'kot pantolon',
      'tişört',
      'mayolar',
      'tek parça mayo',
      'mini etek',
      "pijama",
      'koşu ayakkabısı',
      'sandalet',
      'pareo',
      'banyo bonesi',
      'güneş gözlüğü',
      'güneş gözlükleri',
      'yüzme şortu'
    ]
  },
  'Hobi ve Eğlence': {
    'Müzik': [
      'akordeon',
      'akustik gitar',
      'banjo',
      'fagot',
      'kaset',
      'kaset çalar',
      'CD çalar',
      'çello',
      'kornet',
      'davul',
      'davul çubuğu',
      'elektrikli gitar',
      'flüt',
      'fransız kornosu',
      'büyük piyano',
      'marimba',
      'pan flüt',
      'saksafon',
      'çelik davul',
      'trombon',
      'dikey piyano',
      'keman'
    ],
    'Oyun': [
      'balon',
      'dürbün',
      'yapboz',
      'joystick',
      'dağ çadırı',
      'boya fırçası',
      'rüzgar gülü',
      'uyku tulumu',
      'oyuncak ayı',
      'daktilo klavyesi',
      'çizgi roman',
      'bulmaca'
    ]
  },
  'Spor ve Outdoor': {
    'Gym': [
      'halter',
      'tandem bisiklet',
      'yay',
      'dambıl',
      'dağ bisikleti',
      'direk',
      'kum torbası'
    ],
    'Koruma': [
      'yüzme başlığı',
      'kurşun geçirmez yelek',
      'kask',
      'disk freni',
      'futbol kaskı',
      'diz koruyucu',
      'şnorkel'
    ],
    'Top': [
      'beyzbol',
      'basketbol',
      'kroket topu',
      'golf topu',
      'pinpon topu',
      'hokey puku',
      'raket',
      'ragbi topu',
      'futbol topu',
      'tenis topu',
      'voleybol',
      'düdük'
    ]
  },
  'Diğer': {
    'Diğer': [
      'Yara Bandı',
      'barometre',
      'kuş yuvası',
      'şişe kapağı',
      'plaket',
      'mum',
      'araba aynası',
      'karton',
      'araba tekerleği',
      'kombinasyon kilidi',
      'koltuk değneği',
      'bulaşık bezi',
      'bayrak direği',
      'gaz maskesi',
      'çekiç',
      'sepet',
      'balta',
      'petek',
      'lens kapağı',
      'çakmak',
      'manyetik pusula',
      'kibrit çöpü',
      'fare kapanı',
      'boyunluk',
      'yağ filtresi',
      'oksijen maskesi',
      'asma kilit',
      'kumbarası',
      'hap şişesi',
      'plastik torba',
      'gazoz şişesi',
      'saksı',
      'çömlekçi çarkı',
      'namazlık',
      'çengelli iğne',
      'vida',
      'tornavida',
      'alışveriş sepeti',
      'alışveriş arabası',
      'kayak maskesi',
      'boşluk tuşu',
      'salıncak',
      'yüksük',
      'tripod',
      'şemsiye',
      'cüzdan',
      'su şişesi',
      'su sürahisi',
      'guacamole',
      'trifle',
      'Fransız ekmeği',
      'simit',
      'pretzel',
      'cheeseburger',
      'sosisli sandviç',
      'püre',
      'mantar',
      'carbonara',
      'çikolata sosu',
      'hamur',
      'rulo köfte',
      'yumurta likörü',
      'papatya',
      'kestane'
    ]
  },
};
